export interface Product {
    id: number;
    name: string;
    description: string;
    price: number;
    stock: number;
    imageUrl: string;
  }
  
  export const products: Product[] = [
    {
      id: 1,
      name: "Alifie Relaxantă",
      description: "Ingrediente naturale pentru un efect calmant.",
      price: 50.0,
      stock: 100,
      imageUrl: "/produse-imagini/a-relax.webp",
    },
    {
      id: 2,
      name: "Alifie Anti-Inflamatoare",
      description: "Calmează durerile și reduce inflamația.",
      price: 70.0,
      stock: 50,
      imageUrl: "images/product2.jpg",
    },
    {
      id: 3,
      name: "Alifie Revitalizantă",
      description: "Conferă pielii o senzație de prospețime și revitalizare.",
      price: 65.0,
      stock: 75,
      imageUrl: "images/product3.jpg",
    },
    {
      id: 4,
      name: "Alifie Regenerantă",
      description: "Ajută la regenerarea pielii afectate.",
      price: 80.0,
      stock: 40,
      imageUrl: "images/product4.jpg",
    },
    {
      id: 5,
      name: "Alifie pentru Masaj",
      description: "Perfectă pentru relaxare și tonifiere.",
      price: 60.0,
      stock: 90,
      imageUrl: "images/product5.jpg",
    },
    {
      id: 6,
      name: "Alifie pentru Articulații",
      description: "Oferă suport articulațiilor și reduce disconfortul.",
      price: 85.0,
      stock: 60,
      imageUrl: "images/product6.jpg",
    },
    {
      id: 7,
      name: "Alifie pentru Piele Sensibilă",
      description: "Hidratează și protejează pielea delicată.",
      price: 55.0,
      stock: 120,
      imageUrl: "images/product7.jpg",
    },
    {
      id: 8,
      name: "Alifie Antiseptică",
      description: "Ideală pentru mici răni și zgârieturi.",
      price: 75.0,
      stock: 70,
      imageUrl: "images/product8.jpg",
    },
    {
      id: 9,
      name: "Alifie pentru Arsuri",
      description: "Calmează și accelerează vindecarea arsurilor ușoare.",
      price: 90.0,
      stock: 30,
      imageUrl: "images/product9.jpg",
    },
    {
      id: 10,
      name: "Alifie pentru Ten",
      description: "Revitalizează și hidratează tenul obosit.",
      price: 50.0,
      stock: 150,
      imageUrl: "images/product10.jpg",
    },
    {
      id: 11,
      name: "Alifie pentru Varice",
      description: "Reduce senzația de greutate la nivelul picioarelor.",
      price: 88.0,
      stock: 35,
      imageUrl: "images/product11.jpg",
    },
    {
      id: 12,
      name: "Alifie Antifungică",
      description: "Ajută la combaterea infecțiilor fungice.",
      price: 60.0,
      stock: 110,
      imageUrl: "images/product12.jpg",
    },
    {
      id: 13,
      name: "Alifie pentru Vergeturi",
      description: "Reduce vizibilitatea vergeturilor și îmbunătățește elasticitatea pielii.",
      price: 95.0,
      stock: 45,
      imageUrl: "images/product13.jpg",
    },
    {
      id: 14,
      name: "Alifie Calmanta",
      description: "Ideală pentru pielea iritată și roșeață.",
      price: 70.0,
      stock: 80,
      imageUrl: "images/product14.jpg",
    },
    {
      id: 15,
      name: "Alifie Antirid",
      description: "Îmbunătățește elasticitatea pielii și reduce ridurile fine.",
      price: 120.0,
      stock: 20,
      imageUrl: "images/product15.jpg",
    },
    {
      id: 16,
      name: "Alifie pentru Picioare",
      description: "Revigorează și hidratează pielea uscată de pe picioare.",
      price: 65.0,
      stock: 100,
      imageUrl: "images/product16.jpg",
    },
    {
      id: 17,
      name: "Alifie Anticelulită",
      description: "Contribuie la reducerea aspectului de coajă de portocală.",
      price: 85.0,
      stock: 50,
      imageUrl: "images/product17.jpg",
    },
    {
      id: 18,
      name: "Alifie pentru Relaxare Musculară",
      description: "Efect rapid pentru mușchii obosiți și încordați.",
      price: 80.0,
      stock: 65,
      imageUrl: "images/product18.jpg",
    },
    {
      id: 19,
      name: "Alifie pentru Cicatrici",
      description: "Ajută la reducerea cicatricilor recente și vechi.",
      price: 100.0,
      stock: 30,
      imageUrl: "images/product19.jpg",
    },
    {
      id: 20,
      name: "Alifie pentru Mâini",
      description: "Protejează și hidratează pielea mâinilor expusă la condiții dure.",
      price: 55.0,
      stock: 120,
      imageUrl: "images/product20.jpg",
    },
  ];
  